import React from 'react';

const MyItem = () => {
    return (
        <div>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos quae dolorum cum, fugiat suscipit eligendi veritatis omnis exercitationem doloremque. Et vero perferendis reprehenderit officiis doloremque iure maxime tempore totam vitae impedit perspiciatis, suscipit numquam assumenda alias soluta quia pariatur inventore, reiciendis ab voluptas, voluptatum consectetur nulla nihil! Maiores, ratione? Atque veritatis nesciunt error, nisi quo maxime expedita inventore quae aliquam provident magni, voluptas eveniet praesentium doloremque perferendis sed laborum iure! Porro sed nostrum laborum facere velit, quae dolore delectus magni consequuntur quasi vero, animi ipsa repellendus. Deserunt, enim sapiente. Corporis adipisci sapiente doloribus at iste pariatur perferendis rem, iusto laboriosam explicabo libero cum dolores ipsam ut? Minus delectus totam quo, vero repellendus nihil illo voluptas ratione eaque corrupti enim unde ut laboriosam explicabo id rem earum suscipit illum. Eaque consequuntur temporibus commodi at officia deserunt exercitationem ab debitis unde rerum? Provident hic quod eaque atque voluptates reiciendis tempore velit! Magni praesentium quae corporis consequuntur, consectetur vero totam dolorum enim, dolores optio sequi qui pariatur expedita veniam cumque fugit repellendus tempora doloribus quasi dolore ipsam eaque sint! Fuga iste assumenda blanditiis ab voluptatibus quo nostrum velit ratione neque. Est dolores quos recusandae reiciendis, inventore unde consequuntur vel, placeat temporibus veritatis nulla quisquam, ex commodi necessitatibus ipsum saepe neque amet nam molestias quod distinctio cupiditate? Atque tenetur sed facilis sit, deleniti omnis inventore quos praesentium facere, earum blanditiis, illum excepturi ut alias illo incidunt obcaecati saepe soluta natus aliquid minus quam? Ea repellendus quos quam placeat, facilis excepturi veritatis fuga ipsa possimus aperiam odio doloribus architecto accusamus perferendis sequi dolor eaque est hic reprehenderit neque inventore sit earum vero sint. Excepturi ipsa, optio est illo pariatur expedita iste iure omnis odio corporis labore minus cumque eius minima dolorum perferendis sit repudiandae totam aperiam accusamus ipsum quos, blanditiis a. Dicta accusamus dolorum praesentium.
        </div>
    );
};

export default MyItem;