import React from 'react';

const Additem = () => {
    return (
        <div>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellendus ad reiciendis iure, asperiores dignissimos rerum suscipit? Vero amet dolorum unde ex, eius minima neque inventore quis excepturi, sapiente tenetur beatae officiis in deleniti iusto ipsam commodi suscipit sequi, praesentium aperiam! At, sit perspiciatis, quibusdam suscipit deserunt eligendi ducimus temporibus iusto asperiores quisquam ratione laudantium! Explicabo debitis, velit delectus soluta recusandae consequuntur excepturi earum fugit rerum voluptatum non, consectetur quae in reprehenderit ad vel temporibus culpa minima distinctio perspiciatis ratione. Quibusdam similique dolores eligendi esse consequuntur quisquam iusto corporis! Accusamus perspiciatis fugiat eveniet deserunt deleniti pariatur. Explicabo mollitia nam delectus tenetur ad pariatur dicta minima illum adipisci esse, optio libero in dolorem placeat. Iusto, doloribus. Ad minima tempora doloribus fugit voluptatem, maiores minus veniam aut ea? Quasi labore nam exercitationem error repellendus vitae, accusamus non cumque aperiam in obcaecati, eum autem qui itaque, architecto officiis officia debitis nostrum ad iste fugit veritatis blanditiis voluptatum vel. Iusto, placeat eos beatae pariatur iste aliquam vel error aspernatur. At eos ipsam fugiat ducimus, aliquam optio laudantium placeat sunt dolores ea eum? Accusantium asperiores consequatur magnam perspiciatis veniam delectus dolorem voluptates nesciunt in eos beatae, sed rem quod, necessitatibus sunt? Odit delectus harum placeat maxime vero asperiores nemo suscipit consequuntur nulla nobis dignissimos eligendi quos, itaque recusandae aliquam enim non. Quam non error itaque officiis at molestias nisi eaque unde sapiente consequatur ipsa adipisci blanditiis dicta, tenetur nemo temporibus tempora magnam voluptates vero accusamus assumenda nam repellat. Minima doloribus amet odio, error labore molestias iste maxime enim nam obcaecati, cumque porro voluptates fugiat! Sed laudantium laborum quidem illo perferendis. Modi velit odit quis iure corrupti soluta laborum sit praesentium sequi dignissimos, voluptatibus iste quod ipsa odio ea doloremque animi enim officiis. Architecto, perferendis nisi, unde voluptates eius nulla ea facere atque veniam tempora expedita ducimus?
        </div>
    );
};

export default Additem;